site_name: Steno Documentation
site_url: https://mattmtong.github.io/steno-documentation/

nav:
  - S-, T-, K-, A, *, E, -T, -S, -R: 'Chapter-1.md'
  - Code: 'code-examples.md'
  - Diagram: 'diagram-examples.md'

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/typewriter
  favicon: material/typewriter
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@james-willett
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2024 Matthew M. Tong